const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log('languages array', languages);
var firstElement = 'html';
console.log(' the first element of the array is', firstElement);
var thirdElement = 'javascript';
console.log('the 3rd element of the array is', thirdElement);
var length = languages.length;
console.log('The length of the array is', length);
var lastElement = 'postgres';
console.log('The last element of the array is', lastElement);
